name: "Lambda Deploy"
description: "Deploy Zip of code for Lambda function to AWS Lambda"
inputs:
  assume-role-arn:
    required: true
  env-name:
    required: true
  dir-name:
    required: true

runs:
    using: "composite"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.assume-role-arn }}
          aws-region: ap-northeast-1

      - name: Deploy Lambda
        shell: bash
        run: |
          aws lambda update-function-code \
          --function-name ${{ inputs.env-name }}-${{ inputs.dir-name }} \
          --zip-file fileb://tmp/${{ inputs.dir-name }}/function.zip
