name: Dev AWS Lambda Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  generate-zip:
    name: generate-zip
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Zip
        run: |
          make generate

      - name: Upload Zip Migrateuser
        uses: actions/upload-artifact@v4
        with:
          name: migrateuser
          path: ./tmp/migrateuser/function.zip

      - name: Upload Zip Presignup
        uses: actions/upload-artifact@v4
        with:
          name: presignup
          path: ./tmp/presignup/function.zip

  deploy:
    name: deploy
    needs: [generate-zip]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Lambda Migateuser
        uses: ./.github/actions/lambda-deploy
        with:
          assume-role-arn: ${{ vars.ASSUME_ROLE_ARN_DEV }}
          env-name: dev
          dir-name: migrateuser

      - name: Deploy Lambda Presignup
        uses: ./.github/actions/lambda-deploy
        with:
          assume-role-arn: ${{ vars.ASSUME_ROLE_ARN_DEV }}
          env-name: dev
          dir-name: presignup

