name: Dev Lambda Deploy

on:
  # TODO 以下のpush句消す
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-zip:
    name: deploy-zip
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy zip migrateuser
        uses: ./.github/actions/lambda-deploy
        with:
          assume-role-arn: ${{ vars.ASSUME_ROLE_ARN_DEV }}
          env-name: dev
          dir-name: migrateuser

      - name: Deploy zip presignup
        uses: ./.github/actions/lambda-deploy
        with:
          assume-role-arn: ${{ vars.ASSUME_ROLE_ARN_DEV }}
          env-name: dev
          dir-name: presignup

